{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: horizon-issuer
    name: horizon-issuer-clusterissuer-viewer-role
rules:
    - apiGroups:
        - horizon.evertrust.io
      resources:
        - clusterissuers
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - horizon.evertrust.io
      resources:
        - clusterissuers/status
      verbs:
        - get
{{- end }}
