{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "horizon-issuer.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "horizon-issuer.resourceName" (dict "suffix" "issuer-viewer-role" "context" $) }}
rules:
- apiGroups:
  - horizon.evertrust.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - horizon.evertrust.io
  resources:
  - issuers/status
  verbs:
  - get
{{- end }}
