# permissions for end users to view issuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: issuer-viewer-role
rules:
- apiGroups:
  - horizon.k8s.evertrust.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - horizon.k8s.evertrust.io
  resources:
  - issuers/status
  verbs:
  - get
