{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "horizon-issuer.fullname" . }}
rules:
  # Leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests", "certificates"]
    verbs: ["get", "list", "update", "watch"]

  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/finalizers"]
    verbs: ["update"]

  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/status"]
    verbs: ["get", "patch", "update"]

  - apiGroups: ["horizon.evertrust.io"]
    resources: ["clusterissuers", "issuers"]
    verbs: ["*"]

  # Issuers and ClusterIssuers
  - apiGroups: ["horizon.evertrust.io"]
    resources: ["clusterissuers/finalizers", "issuers/finalizers"]
    verbs: ["update"]

  - apiGroups: ["horizon.evertrust.io"]
    resources: ["clusterissuers/status", "issuers/status"]
    verbs: ["get", "patch", "update"]

  # Cert-maanger approver
  - apiGroups: ["cert-manager.io"]
    resources: ["signers"]
    verbs: ["approve"]

  # Ingress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
{{ end }}