apiVersion: horizon.k8s.evertrust.io/v1alpha1
kind: Issuer
metadata:
  name: issuer-sample
spec:
  url: https://horizon-qa.evertrust.io
  authSecretName: issuer-sample-credentials
  profile: IssuerProfile
