apiVersion: horizon.evertrust.io/v1beta1
kind: ClusterIssuer
metadata:
  name: horizon-clusterissuer
spec:
  url: https://horizon-28.qa.evertrust.io/
  authSecretName: horizon-credentials
  profile: issuer