apiVersion: horizon.evertrust.io/v1beta1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: horizon-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-sample
spec:
  # TODO(user): Add fields here
