apiVersion: horizon.k8s.evertrust.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: clusterissuer-sample
spec:
  url: https://horizon.company.com
  authSecretName: clusterissuer-sample-credentials
  profile: IssuerProfile
