apiVersion: horizon.evertrust.io/v1beta1
kind: Issuer
metadata:
  name: issuer-sample
spec:
  url: https://horizon.company.com
  authSecretName: clusterissuer-sample-credentials
  profile: IssuerProfile
  defaultTemplate:
    team: team1
    owner: owner1
    contactEmail: owner1@company.com
    labels:
      cluster: mycluster
      env: dev
  overrideTemplate:
    owner: owner1
    team: team1
    contactEmail: owner1@company.com
    labels:
      cluster: mycluster
      env: dev