name: E2E Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Disable containerd image store
        # Workaround for https://github.com/kubernetes-sigs/kind/issues/3795
        run: |
          sudo mkdir -p /etc/docker
          docker --version || true
          containerd --version || true
          [ -s "/etc/docker/daemon.json" ] && {
            cat "/etc/docker/daemon.json" | jq '. + {"features":{"containerd-snapshotter": false}}' | sudo tee /etc/docker/daemon.$$
          } || {
            echo '{"features":{"containerd-snapshotter": false}}' | sudo tee /etc/docker/daemon.$$
          }
          sudo mv -f /etc/docker/daemon.$$ /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Setup Mise
        uses: jdx/mise-action@v2

      - name: Fetch license
        run: |
          printf "${{ secrets.LICENSE }}" >> test/assets/horizon.lic

      - name: Run E2E tests
        run: mise test:e2e
